/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    // But you can create a sidebar manually

    tutorialSidebar: [
        'getting-started',
        {
            type: 'category',
            label: 'General Commands',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'general-commands',
                },
            ],
        },
        {
            type: 'category',
            label: 'Language Specific Commands',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'language',
                },
            ],
        },
        'comments',
        'configuration',
    ],
}
